version: 2.1

executors:
  golang-terraform:
    docker:
      - image: circleci/golang:stretch

defaults: &defaults
  executor: golang-terraform

commands:
  install-common-packages:
    steps:
      - run:
          name: 'Install required packages'
          command: |
            sudo wget --quiet https://releases.hashicorp.com/terraform/0.13.4/terraform_0.13.4_linux_amd64.zip && \
            sudo unzip terraform_0.13.4_linux_amd64.zip && \
            sudo mv terraform /usr/local/bin/ && \
            sudo rm terraform_0.13.4_linux_amd64.zip
  run-tests:
    steps:
      - checkout
      - install-common-packages
      - run:
          name: 'Run Tests'
          command: |
            cd test && go test -v -timeout 30m
jobs:
  run-tests:
    <<: *defaults
    steps:
      - run-tests
workflows:
  version: 2
  test-terraform:
    jobs:
      - run-tests